version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./config/docker/backend/Dockerfile
      args:
        USER_ID: 1000
        APP_STATUS: development
    command: celery -A src.celery.celery_app worker
    volumes:
      - ./backend:/app
    env_file:
      - ./config/environment_variables/.env
    depends_on:
      - celerybeat
    restart: always
  celerybeat:
    build:
      context: .
      dockerfile: ./config/docker/backend/Dockerfile
      args:
        USER_ID: 1000
        APP_STATUS: development
    command: celery -A src.celery.celery_app beat
    env_file:
      - ./config/environment_variables/.env
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:6.2-alpine

networks:
  default:
    external:
      name: stock_buyer_network
