STOCK_TICKERS = [
    '1AB',
    '2CD',
    '3EF',
    '4GH',
    '5IJ',
    '6KL',
    '7MN',
    '8OP',
    '9RS',
    '10T',
]
MIN_TRADE_TICKER_QUANTITY = 1
MAX_TRADE_TICKER_QUANTITY = 100
MIN_TRADE_TICKER_PRICE = 50
MAX_TRADE_TICKER_PRICE = 5000
