version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./config/docker/backend/Dockerfile
      args:
        USER_ID: 1000
        APP_STATUS: development
    command: uvicorn --reload --host 0.0.0.0 --port 8001 src.main:app
    volumes:
      - ./backend:/app
    env_file:
      - ./config/environment_variables/.env
    ports:
      - 8001:8001
    depends_on:
      - redis
    networks:
      # for inner network
      default: { }
      # name for external network
      stock_buyer_network:
        aliases:
          - controller-server
  redis:
    image: redis:6.2
    env_file:
      - ./config/environment_variables/.env
    command: redis-server --save 30 1 --requirepass "${REDIS_PASSWORD}"
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_db:/data

volumes:
  redis_db:

networks:
  default: {}
  stock_buyer_network:
    external: true
