version: "3.8"

services:
  app: &app
    build:
      context: .
      dockerfile: ./config/docker/backend/Dockerfile
      args:
        USER_ID: 1000
        APP_STATUS: development
    command: /start
    volumes:
      - ./backend:/app
    env_file:
      - ./config/environment_variables/.env.dev
    networks:
      reporter_network:
      stock_buyer_network:
        aliases:
          - reporter
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - db_test
  db:
    image: postgres:14.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/environment_variables/.env.dev
    networks:
      reporter_network:
  db_test:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=db_test
      - POSTGRES_PASSWORD=db_test
      - POSTGRES_DB=db_test
    networks:
      reporter_network:
  redis:
    image: redis:6.2-alpine
    networks:
      reporter_network:

  celery_worker:
    <<: *app
    command: /start-worker
    ports: [ ]
    networks:
      reporter_network:
      #stock_buyer_network:

volumes:
  postgres_data:

networks:
  reporter_network:
  stock_buyer_network:
    external: true
