version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./config/docker/backend/Dockerfile
      args:
        USER_ID: 1000
        APP_STATUS: development
    command: celery -A src.celery.celery_app worker
    volumes:
      - ./backend:/app
    env_file:
      - ./config/environment_variables/.env
    restart: always
    depends_on:
      - redis
    networks:
      - fill_server_network
      - stock_buyer_network

  redis:
    image: redis:6.2-alpine
    networks:
      - fill_server_network

networks:
  fill_server_network:
  stock_buyer_network:
    external: true
