version: "3.8"

services:
  app: &app
    build:
      context: .
      dockerfile: ./config/docker/backend/Dockerfile
      args:
        USER_ID: 1000
        APP_STATUS: development # look for entrypoint
    command: /app/start
    env_file:
      - ./config/environment_variables/.env.dev
    depends_on:
      - redis
    volumes:
      - ./backend/src:/app/src
    networks:
      stock_screener_network:
      stock_buyer_network:
        aliases:
          - stock_screener
  redis:
    image: redis:6.2-alpine
    networks:
      stock_screener_network:

  celery_beat:
    <<: *app
    command: /app/start-celerybeat
    ports: [ ]
    networks:
      stock_screener_network:

  celery_worker:
    <<: *app
    command: /app/start-worker
    ports: [ ]
    networks:
      stock_screener_network:
      stock_buyer_network:

networks:
  stock_screener_network:
  stock_buyer_network:
    external: true
